[repositories]
rugix-extra = { git = "https://github.com/rugix/rugix-extra.git", branch = "v0.8" }

[systems.imx91-frdm]
layer = "customized"
architecture = "arm64"
target = "unknown"

[systems.imx91-frdm.image]
size = "2G"

[systems.imx91-frdm.image.layout]
type = "gpt"
raw-blobs = [
    { file = "imx-boot", offset = "32KiB" },
]

[[systems.imx91-frdm.image.layout.partitions]]
size = "64MiB"
type = "EBD0A0A2-B9E5-4433-87C0-68B6B72699C7"
filesystem = { type = "fat32" }
root = "config"

[[systems.imx91-frdm.image.layout.partitions]]
filesystem = { type = "ext4" }
root = "system"
